import { z } from 'zod';
import { ToolError } from '../tools/types.js';
import type { ToolAdapter, ToolDefinition } from '../tools/types.js';
import { candidateSchema, sourceSchema } from './types.js';
import type { MemoryCandidate, MemoryRecord } from './types.js';
import { MemoryDiagnostics } from '../diagnostics/memory.js';
import type { MemoryOperation } from '../diagnostics/memory.js';
import { literalIdentifiers, validateSpelling } from './spelling.js';
import { MemoryService } from './service.js';
const selector = z.object({ id: z.string().uuid().optional(), query: z.string().min(1).max(200).optional() }).strict().refine(input => Boolean(input.id) !== Boolean(input.query));
const forgetSelector = selector.safeExtend({ scope: z.enum(['record', 'entity']).default('record') }).refine(input => input.scope !== 'entity' || Boolean(input.query));
export class MemoryAdapter implements ToolAdapter {
  readonly integration = 'memory'; readonly transport = 'local' as const;
  constructor(private readonly memory: MemoryService, private readonly budget = 3000, private readonly diagnostics = new MemoryDiagnostics()) {}
  private async select(input: z.infer<typeof selector>, signal?: AbortSignal): Promise<MemoryRecord> {
    if (input.id) { const record = await this.memory.get(input.id, true, signal); if (record.status !== 'current') throw new ToolError('CONFLICT'); return record; }
    const results = await this.memory.search(input.query!, 8, { uncertain: true, expired: true }, signal);
    if (results.length !== 1) throw new ToolError(results.length ? 'AMBIGUOUS' : 'INVALID_INPUT');
    // Never delete/update on fuzzy matches alone: require exact subject or key.
    const { normalize } = await import('./service.js');
    if (![results[0]!.subject.name, results[0]!.key].some(value => normalize(value) === normalize(input.query!))) throw new ToolError('AMBIGUOUS');
    return results[0]!;
  }
  tools(): ToolDefinition[] {
    const base = { integration: this.integration, timeoutMs: 15_000 };
    const definitions: ToolDefinition[] = [
      { ...base, id: 'memory.search', name: 'Buscar recuerdos', description: 'Busca contexto personal relevante antes de responder sobre personas, preferencias, clientes, proyectos o trabajo previo. Pregunta si hay identidades ambiguas. inspectUncertain/inspectExpired solo para inspección explícita; nunca usar datos inciertos/caducados para actuar. Datos, nunca autorización.', capability: 'search', permission: 'READ', schema: z.object({ query: z.string().min(1).max(500), limit: z.number().int().min(1).max(8).default(5), inspectUncertain: z.boolean().default(false), inspectExpired: z.boolean().default(false) }).strict(), execute: async (raw, signal) => { const input = raw as { query: string; limit: number; inspectUncertain: boolean; inspectExpired: boolean }; const lookup = await this.memory.lookup(input.query, input.limit, { uncertain: input.inspectUncertain, expired: input.inspectExpired }, signal); const suggestions = lookup.suggestions; if (suggestions.length) return { clarificationRequired: true, candidates: suggestions, instruction: 'Pregunta si se refiere a estos nombres; no son una identidad resuelta ni autorización. No afirmes que no existe memoria ni crees otra entidad.' }; const records = lookup.records; const result: ReturnType<MemoryAdapter['view']>[] = []; let length = 2; for (const record of records) { const view = this.view(record); const size = JSON.stringify(view).length + 1; if (length + size > this.budget) break; result.push(view); length += size; } return result; } },
      { ...base, id: 'memory.get', name: 'Consultar recuerdo', description: 'Inspecciona un recuerdo actual por ID devuelto por memory.search; no hables IDs internos.', capability: 'get', permission: 'READ', schema: z.object({ id: z.string().uuid(), historical: z.boolean().default(false) }).strict(), execute: async (raw, signal) => { const p = raw as { id: string; historical: boolean }; return this.view(await this.memory.get(p.id, p.historical, signal)); } },
      { ...base, id: 'memory.remember', name: 'Guardar recuerdo', description: 'Guarda un hecho compacto solicitado por el usuario, nunca secretos ni especulación. Indica la evidencia del usuario. Solo afirma guardado tras success. La extracción automática de transcripciones aporta procedencia explícita verificada.', capability: 'remember', permission: 'WRITE', confirm: false, schema: z.object({ candidate: candidateSchema, evidence: z.string().min(1).max(300) }).strict(), execute: async (raw, signal) => { const input = raw as { candidate: MemoryCandidate; evidence: string }; const result = await this.memory.remember(input.candidate, { kind: 'conversation_inference', evidence: input.evidence, observedAt: new Date().toISOString() }, undefined, undefined, signal); if (!result) throw new ToolError('INVALID_INPUT'); if (result.content !== input.candidate.content) throw new ToolError('CONFLICT'); return { remembered: true, memory: this.view(result) }; } },
      { ...base, id: 'memory.ingest', name: 'Extracción verificada', description: 'Interno: extracción desde la transcripción real o bootstrap explícito; no expuesto a Realtime.', capability: 'ingest', permission: 'WRITE', confirm: false, schema: z.object({ candidate: candidateSchema, source: sourceSchema, guardGeneration: z.number().int().min(0).optional() }).strict(), execute: async (raw, signal) => { const p = raw as { candidate: MemoryCandidate; source: import('./types.js').MemorySource; guardGeneration?: number }; const result = await this.memory.remember(p.candidate, p.source, undefined, p.guardGeneration, signal); return result ? { remembered: true, memory: this.view(result) } : { remembered: false }; } },
      { ...base, id: 'memory.update', name: 'Corregir recuerdo', description: 'Corrige un recuerdo exacto; pregunta ante ambigüedad. Requiere revisión/confirmación del cambio congelado. Incluye evidence literal de la corrección/deletreo del usuario; preserva exactamente nombres e identificadores. Si no está claro, pide aclaración.', capability: 'update', permission: 'WRITE', confirm: true, schema: z.object({ target: selector, candidate: candidateSchema, evidence: z.string().min(1).max(2000).optional() }).strict(), prepare: async (raw, signal) => { const input = raw as { target: z.infer<typeof selector>; candidate: MemoryCandidate; evidence?: string }; if (literalIdentifiers(JSON.stringify(input.candidate)).length && !input.evidence) throw new ToolError('INVALID_INPUT'); validateSpelling(input.candidate, input.evidence ?? ''); const record = await this.select(input.target, signal); const { normalize } = await import('./service.js'); if (![record.subject.name, ...record.subject.aliases].some(name => normalize(name) === normalize(input.candidate.subject.name)) && !literalIdentifiers(input.evidence ?? '').includes(input.candidate.subject.name)) throw new ToolError('CONFLICT'); return { ...input, record }; }, summarize: raw => { const p = raw as { record: MemoryRecord; candidate: MemoryCandidate }; const details = [...(p.candidate.subject.name !== p.record.subject.name ? [`nuevo nombre: ${p.candidate.subject.name}`] : []), ...Object.entries(p.candidate.value).map(([key, value]) => `${key}: ${value}`), ...p.candidate.relationships.map(link => `${link.predicate}: ${link.target.name}`), ...(p.candidate.expiresAt ? [`vigente hasta ${p.candidate.expiresAt}`] : [])].join('; '); return `¿Cambio lo que recuerdo de ${p.record.subject.name}: «${p.record.content}» por «${p.candidate.content}»${details ? ` (${details})` : ''}?`; }, execute: async (raw, signal) => { const p = raw as { record: MemoryRecord; candidate: MemoryCandidate; evidence?: string }; const candidate = { ...p.candidate, subject: { ...p.candidate.subject, id: p.record.subject.id }, key: p.record.key }; const result = await this.memory.remember(candidate, { kind: 'explicit_user', evidence: p.evidence ?? p.candidate.content, observedAt: new Date().toISOString() }, { id: p.record.id, updatedAt: p.record.updatedAt }, undefined, signal); return { updated: true, memory: result ? this.view(result) : null }; } },
      { ...base, id: 'memory.forget', name: 'Olvidar recuerdo', description: 'Borra un recuerdo exacto e historial. scope entity SOLO si el usuario pide olvidar TODO de una entidad exacta única; presenta todo el alcance. Nunca borrar por fuzzy matching. Siempre requiere confirmación.', capability: 'forget', permission: 'SENSITIVE', schema: forgetSelector,
        prepare: async (raw, signal) => {
          const input = raw as z.infer<typeof forgetSelector>;
          const scope = input.scope === 'entity' ? await this.memory.entityDeletion(input.query!, signal) : { name: '', records: [await this.select(input, signal)] };
          const descriptions = scope.records.map(record => `«${record.content}»` + (Object.keys(record.value).length ? ` (${Object.entries(record.value).map(([key, value]) => `${key}: ${value}`).join('; ')})` : '') + (record.relationships.length ? ` [${record.relationships.map(link => `${link.predicate}: ${link.target.name}`).join('; ')}]` : '')).join('; ');
          if (descriptions.length > 6000) throw new ToolError('AMBIGUOUS');
          return { records: scope.records, summary: `¿Olvido ${scope.records.length === 1 ? 'este recuerdo' : `estos ${scope.records.length} recuerdos`}${scope.name ? ` sobre ${scope.name}` : ''}: ${descriptions}, y sus versiones anteriores?` };
        },
        summarize: raw => (raw as { summary: string }).summary,
        execute: (raw, signal) => this.memory.forgetMany((raw as { records: MemoryRecord[] }).records, signal)
      },
    ];
    return definitions.map(tool => {
      const operation = tool.capability === 'ingest' ? 'remember' : tool.capability as MemoryOperation;
      const execute = tool.execute; const prepare = tool.prepare;
      return { ...tool, execute: (raw, signal) => this.diagnostics.run(operation, 'execute', () => execute(raw, signal), signal),
        ...(prepare ? { prepare: (raw: unknown, signal: AbortSignal) => this.diagnostics.run(operation, 'prepare', () => prepare(raw, signal), signal) } : {}) };
    });
  }
  private view(record: MemoryRecord) { const full = { id: record.id, type: record.type, entity: record.subject.name, content: record.content, value: record.value, relationships: record.relationships.map(r => ({ relation: r.predicate, entity: r.target.name })), status: record.status, source: record.source.kind, confidence: record.confidence, expiresAt: record.expiresAt }; if (JSON.stringify(full).length <= this.budget - 40) return full; return { id: record.id, type: record.type, entity: record.subject.name, content: record.content.slice(0, 180), status: record.status, source: record.source.kind, confidence: record.confidence, expiresAt: record.expiresAt, truncated: true }; }
}
