import { createHash,randomUUID } from 'node:crypto';
import { z } from 'zod';
import type { ToolDefinition } from '../../tools/types.js';
import { ToolError } from '../../tools/types.js';
import { candidateSchema,intentSchema,authorizationSchema,resultSchema } from './contracts.js';
import type { Candidate,FrozenIntent,Authorization,ActionState,ConsequentialResult,TrustedContext } from './contracts.js';
import { PrivateExecutionJournal } from './journal.js';
const terminal=new Set<ActionState>(['SUCCESS','FAILURE','UNKNOWN','CANCELLED','REJECTED','EXPIRED','INVALIDATED']);
const inputSchema=z.object({recipientHint:z.string().min(1).max(120),text:z.string().min(1).max(2000)}).strict();
const proofSchema=z.object({simulationOnly:z.literal(true),evidence:z.literal('SIMULATED_MESSAGE_ACCEPTED')}).strict();
interface Entry {intent:FrozenIntent;state:ActionState;confirmationId?:string;authorization?:Authorization;result?:ConsequentialResult;work?:Promise<ConsequentialResult>;cancelled?:boolean;controller?:AbortController;}
export interface SimulatedExecutor {readonly simulationOnly:true;execute(intent:FrozenIntent,signal:AbortSignal):Promise<z.infer<typeof proofSchema>>;}
const candidateOf=(intent:FrozenIntent)=>{const {intentId:_id,kind:_kind,createdAt:_created,expiresAt:_expires,summary:_summary,...candidate}=intent;return candidateSchema.parse(candidate);};
const digest=(x:unknown)=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
function freeze<T>(x:T):T {if(x&&typeof x==='object'){for(const value of Object.values(x))freeze(value);Object.freeze(x);}return x;}
// Foundation only: this class is NOT installed in createToolRuntime, protocol,
// extension or BrowserProvider. Its sole executor must explicitly be simulated.
export class ConsequentialFoundation {
 private entries=new Map<string,Entry>();private recovered=new Map<string,'SUCCESS'|'FAILURE'|'UNKNOWN'>();private initialized=false;private unresolved=false;
 constructor(private readonly journal:PrivateExecutionJournal,private readonly context:(signal:AbortSignal)=>Promise<TrustedContext>,private readonly sessionId:string,private readonly simulator:SimulatedExecutor,private readonly now=Date.now,private readonly cancelPending?:(confirmationId:string)=>void){if(simulator.simulationOnly!==true)throw new ToolError('REJECTED');}
 async initialize(){if(this.initialized)return;for(const row of await this.journal.recover()){this.recovered.set(row.intentId,row.state==='RESERVED'?'UNKNOWN':row.state);if(row.state==='UNKNOWN')this.unresolved=true;}this.initialized=true;}
 private access(context:TrustedContext){if(!context.chromePermission||!context.siteAuthorized||!context.grantValid||context.grantExpiresAt<=this.now())throw new ToolError('REJECTED');const candidate=candidateSchema.parse(context.candidate);if(candidate.backendSessionId!==this.sessionId)throw new ToolError('REJECTED');return candidate;}
 async prepare(raw:unknown,signal:AbortSignal):Promise<{intentId:string}>{if(this.unresolved)throw new ToolError('EXECUTION_UNKNOWN');if(!this.initialized||this.entries.size>=100)throw new ToolError('UNCONFIGURED');const request=inputSchema.parse(raw);signal.throwIfAborted();const context=await this.context(signal);signal.throwIfAborted();const candidate=this.access(context);
 if(candidate.recipient.displayName!==request.recipientHint||candidate.content.text!==request.text)throw new ToolError('CONFLICT');
 const now=this.now();const intent=freeze(intentSchema.parse({...candidate,intentId:randomUUID(),kind:'SEND_MESSAGE',createdAt:now,expiresAt:Math.min(now+60_000,context.grantExpiresAt),summary:`SIMULACIÓN: ¿Confirmás enviar a ${JSON.stringify(candidate.recipient.displayName)} (${JSON.stringify(candidate.recipient.identity)}) este texto exacto: ${JSON.stringify(candidate.content.text)}? No se enviará ningún mensaje real.`}));
 this.entries.set(intent.intentId,{intent,state:'RESOLVING'});this.entry(intent.intentId).state='FROZEN';return {intentId:intent.intentId};}
 private entry(id:string){const e=this.entries.get(id);if(!e||e.intent.backendSessionId!==this.sessionId||this.recovered.has(id))throw new ToolError('EXPIRED');return e;}
 private failure(e:Entry,state:ActionState,reason:ConsequentialResult['reason']){e.state=state;e.result=resultSchema.parse({intentId:e.intent.intentId,...(e.authorization?{executionId:e.authorization.executionId}:{}),simulationOnly:true,execution:'NOT_EXECUTED',verification:'FAILED',outcome:'CONFIRMED_FAILURE',reason});return e.result;}
 private unknown(e:Entry,reason:ConsequentialResult['reason']){this.unresolved=true;e.state='UNKNOWN';e.result=resultSchema.parse({intentId:e.intent.intentId,executionId:e.authorization!.executionId,simulationOnly:true,execution:'UNKNOWN',verification:'INCONCLUSIVE',outcome:'EXECUTION_UNKNOWN',reason});return e.result;}
 private pending(id:string,confirmationId:string,expiresAt:number){const e=this.entry(id);if(e.state!=='FROZEN'||e.intent.expiresAt<=this.now())throw new ToolError('EXPIRED');e.confirmationId=confirmationId;e.state='WAITING_CONFIRMATION';if(expiresAt<=this.now())this.failure(e,'EXPIRED','EXPIRED');}
 private decided(id:string,confirmationId:string,approved:boolean){const e=this.entry(id);if(e.state!=='WAITING_CONFIRMATION'||e.confirmationId!==confirmationId)throw new ToolError('EXPIRED');if(e.intent.expiresAt<=this.now()){this.failure(e,'EXPIRED','EXPIRED');throw new ToolError('EXPIRED');}if(!approved){this.failure(e,'REJECTED','CANCELLED');return;}e.authorization=freeze(authorizationSchema.parse({intentId:id,confirmationId,executionId:randomUUID(),backendSessionId:e.intent.backendSessionId,bindingDigest:digest(candidateOf(e.intent)),deadlineAt:e.intent.expiresAt}));e.state='REVALIDATING';}
 invalidate(intentId:string,reason:'CANCELLED'|'ACCESS_REVOKED'|'PRECONDITION_CHANGED'='CANCELLED'){const e=this.entry(intentId);if(terminal.has(e.state))return;e.cancelled=true;if(['DISPATCH_RESERVED','EXECUTING','VERIFYING'].includes(e.state))this.unknown(e,reason);else this.failure(e,reason==='PRECONDITION_CHANGED'?'INVALIDATED':'CANCELLED',reason);e.controller?.abort();if(e.confirmationId)this.cancelPending?.(e.confirmationId);}
 state(intentId:string){const e=this.entry(intentId);return {intentId,state:e.state,result:e.result?structuredClone(e.result):null};}
 recoveredState(intentId:string){return this.recovered.get(intentId);}
 private async run(e:Entry,signal:AbortSignal):Promise<ConsequentialResult>{const auth=e.authorization!;let reserved=false;let dispatched=false;const controller=new AbortController();e.controller=controller;const abort=()=>controller.abort();signal.addEventListener('abort',abort,{once:true});const timer=setTimeout(abort,Math.max(1,Math.min(15_000,auth.deadlineAt-this.now())));const ensure=()=>{if(e.cancelled||terminal.has(e.state)||controller.signal.aborted||signal.aborted||auth.deadlineAt<=this.now())throw new ToolError('TIMEOUT');};
 const readContext=()=>new Promise<TrustedContext>((resolve,reject)=>{const stop=()=>reject(new ToolError('TIMEOUT'));controller.signal.addEventListener('abort',stop,{once:true});if(controller.signal.aborted)stop();Promise.resolve().then(()=>this.context(controller.signal)).then(resolve,reject).finally(()=>controller.signal.removeEventListener('abort',stop));});
 try{ensure();const context=await readContext();ensure();const current=this.access(context);if(digest(current)!==auth.bindingDigest){return this.failure(e,'INVALIDATED','PRECONDITION_CHANGED');}
 e.state='DISPATCH_RESERVED';await this.journal.reserve({intentId:e.intent.intentId,executionId:auth.executionId,state:'RESERVED',updatedAt:this.now()});reserved=true;ensure();
 // Journal I/O is asynchronous: repeat authoritative READ immediately before
 // the possible effect, without changing the frozen bindings or authorization.
 const finalContext=this.access(await readContext());ensure();if(digest(finalContext)!==auth.bindingDigest){await this.journal.finish(auth.executionId,'FAILURE',this.now());reserved=false;return this.failure(e,'INVALIDATED','PRECONDITION_CHANGED');}
 e.state='EXECUTING';let rejectAbort!:(error:ToolError)=>void;const interrupted=new Promise<never>((_resolve,reject)=>{rejectAbort=reject;});const stop=()=>rejectAbort(new ToolError('EXECUTION_UNKNOWN'));controller.signal.addEventListener('abort',stop,{once:true});
 let proof;try{dispatched=true;proof=await Promise.race([this.simulator.execute(e.intent,controller.signal),interrupted]);}finally{controller.signal.removeEventListener('abort',stop);}ensure();e.state='VERIFYING';proofSchema.parse(proof);ensure();e.state='SUCCESS';e.result=resultSchema.parse({intentId:e.intent.intentId,executionId:auth.executionId,simulationOnly:true,execution:'ACKNOWLEDGED',verification:'VERIFIED',outcome:'CONFIRMED_SUCCESS',reason:'SIMULATED_EFFECT',evidence:'SIMULATED_MESSAGE_ACCEPTED'});
 // A verified effect is not erased by late cancellation or journal completion.
 await this.journal.finish(auth.executionId,'SUCCESS',this.now()).catch(()=>{});return e.result;
 }catch{if(terminal.has(e.state)&&e.result)return e.result;const result=dispatched?this.unknown(e,controller.signal.aborted||signal.aborted?'TIMEOUT':'DISPATCH_UNCERTAIN'):this.failure(e,'FAILURE',controller.signal.aborted||signal.aborted?'TIMEOUT':e.state==='DISPATCH_RESERVED'&&!reserved?'JOURNAL_UNAVAILABLE':'ACCESS_REVOKED');if(reserved)await this.journal.finish(auth.executionId,dispatched?'UNKNOWN':'FAILURE',this.now()).catch(()=>{});return result;
 }finally{e.controller=undefined;clearTimeout(timer);signal.removeEventListener('abort',abort);}}
 execute(intentId:string,signal:AbortSignal):Promise<ConsequentialResult>{const e=this.entry(intentId);if(e.work)return e.work;if(e.result)return Promise.resolve(e.result);if(e.state!=='REVALIDATING'||!e.authorization)throw new ToolError('REJECTED');e.work=this.run(e,signal);return e.work;}
 // Only a trusted executor lifecycle hook grants execution. Model input contains
 // no confirmationId, executionId, origin, grant or approval boolean.
 simulationTool():ToolDefinition{return {id:'browser.simulateSendMessage',name:'browser_simulateSendMessage',description:'SIMULATION ONLY: no external effect.',integration:'browser',capability:'simulateSendMessage',permission:'SENSITIVE',schema:inputSchema,timeoutMs:18_000,prepare:(raw,signal)=>this.prepare(raw,signal),summarize:raw=>this.entry((raw as {intentId:string}).intentId).intent.summary,
 confirmationLifecycle:{pending:(raw,id,expires)=>this.pending((raw as {intentId:string}).intentId,id,expires),decided:(raw,id,approved)=>this.decided((raw as {intentId:string}).intentId,id,approved),invalidated:(raw,reason)=>{const e=this.entry((raw as {intentId:string}).intentId);if(!terminal.has(e.state))this.failure(e,reason==='expired'?'EXPIRED':'CANCELLED',reason==='expired'?'EXPIRED':'CANCELLED');}},execute:(raw,signal)=>this.execute((raw as {intentId:string}).intentId,signal)};}
}
