import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {randomUUID as id} from 'node:crypto';import {JSDOM} from 'jsdom';
import {PopupDiagnostics,popupTraceSchema} from '../diagnostics/popup.js';import type {PopupTrace} from '../diagnostics/popup.js';import {hostPattern} from '../../extension/src/site-authorization.js';
const settle=()=>new Promise(resolve=>setTimeout(resolve,0));
async function popup(){const dom=new JSDOM(await readFile('extension/popup.html','utf8'),{runScripts:'outside-only'});const rows:PopupTrace[]=[];const waits:{resolve:(x:unknown)=>void;correlationId?:string}[]=[];let refresh=()=>{};
 (dom.window as any).chrome={storage:{local:{get:async()=>({atlasPopupDiagnostics:true})}},runtime:{sendMessage:(message:{correlationId?:string})=>new Promise(resolve=>waits.push({resolve,correlationId:message.correlationId}))},permissions:{onRemoved:{addListener:(f:()=>void)=>{refresh=f;}},onAdded:{addListener:()=>{}}}};
 (dom.window as any).PopupDiagnostics=class extends PopupDiagnostics{constructor(){super(row=>rows.push(row));}};(dom.window as any).hostPattern=hostPattern;Object.defineProperty(dom.window.crypto,'randomUUID',{value:id});dom.window.eval((await readFile('dist/extension/popup.js','utf8')).replace(/^import .*;$/gm,''));await settle();return {dom,rows,waits,refresh:()=>refresh()};}
const state=(origin='https://fixture.example')=>({connected:true,pending:[],authorized:[],sites:[{origin,allowed:true}]});
test('slow popup hydration is measured without fabricating success before state arrives',async()=>{const f=await popup();try{assert.match(f.dom.window.document.querySelector('#state')!.textContent!,/Conectando/);assert.ok(f.rows.some(r=>r.stage==='popup_opened'));assert.ok(f.rows.some(r=>r.stage==='state_requested'));f.waits[0]!.resolve(state());await settle();assert.ok(f.rows.some(r=>r.stage==='state_ready'&&r.durationMs!==undefined));}finally{f.dom.window.close();}});
test('out-of-order popup refresh is diagnosed and cannot overwrite newer hydrated state',async()=>{const f=await popup();try{f.refresh();await settle();f.waits[1]!.resolve(state('https://new.example'));await settle();f.waits[0]!.resolve(state('https://old.example'));await settle();assert.match(f.dom.window.document.querySelector('#sites')!.textContent!,/new.example/);assert.ok(f.rows.some(r=>r.outcome==='OUT_OF_ORDER'));}finally{f.dom.window.close();}});
test('popup close during request discards the late UI response and records CLOSED',async()=>{const f=await popup();try{f.dom.window.dispatchEvent(new f.dom.window.Event('pagehide'));f.waits[0]!.resolve(state());await settle();assert.ok(f.rows.some(r=>r.outcome==='CLOSED'));assert.equal(f.dom.window.document.querySelector('#sites')!.textContent,'');}finally{f.dom.window.close();}});
test('diagnostics default off, whitelist only sanitized fields and tolerate a failed sink',()=>{const rows:PopupTrace[]=[];const diag=new PopupDiagnostics(row=>rows.push(row));diag.event(id(),'authorization_click');assert.equal(rows.length,0);diag.enabled=true;const correlation=id();diag.event(correlation,'permission_result','OK',1.5);assert.deepEqual(rows,[{correlationId:correlation,stage:'permission_result',outcome:'OK',durationMs:1.5}]);assert.equal(popupTraceSchema.safeParse({...rows[0],url:'https://private.example/?token=private',title:'private'}).success,false);diag.event('secret','state_ready');diag.event(id(),'private content' as any);assert.equal(rows.length,1);const broken=new PopupDiagnostics(()=>{throw new Error('private');});broken.enabled=true;assert.doesNotThrow(()=>broken.event(id(),'notification_posted'));});
