import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { runInNewContext } from 'node:vm';
import { JSDOM } from 'jsdom';
const source=await readFile('scripts/whatsapp-structural-probe.js','utf8');
const html='<main id="conversation"><header aria-label="PRIVATE_NAME">PRIVATE_NAME</header><div role="log">PRIVATE_MESSAGE +1234567890<button aria-label="PRIVATE_HISTORY_MESSAGE">PRIVATE</button></div><footer><div contenteditable="true" role="textbox" aria-label="PRIVATE_COMPOSER">PRIVATE_DRAFT</div><button aria-label="Send">PRIVATE_BUTTON</button></footer></main><aside id="contact"><header>PRIVATE_CONTACT</header><span id="phone">+12345678901</span></aside>';
async function run(state:'A'|'B',options:{change?: (doc:Document)=>void;phone?:string;panel?:string;large?:boolean;delayMs?:number}={}) {
 const dom=new JSDOM(options.large?html.replace('</footer>',Array.from({length:60},()=>'<button>PRIVATE</button>').join('')+'</footer>'):html,{url:'https://private.example/path?secret=PRIVATE_URL',pretendToBeVisual:true}),win=dom.window;
 const root=win.document.getElementById('conversation')!,panel=win.document.getElementById(options.panel??'contact')!,field=win.document.getElementById(options.phone??'phone')!;
 const fail=()=>{throw new Error('Forbidden private read or action');};
 const getAttribute=win.HTMLElement.prototype.getAttribute;win.HTMLElement.prototype.getAttribute=function(name:string){if(name==='aria-label'&&this.closest('[role="log"]'))return fail();return getAttribute.call(this,name);};
 win.HTMLElement.prototype.checkVisibility=function(){return !this.closest('[hidden]');};win.HTMLElement.prototype.getBoundingClientRect=()=>({width:10,height:10} as DOMRect);
 for(const property of ['textContent','innerText'])Object.defineProperty(win.HTMLElement.prototype,property,{get:fail,set:fail,configurable:true});
 for(const prototype of [win.HTMLInputElement.prototype,win.HTMLTextAreaElement.prototype])Object.defineProperty(prototype,'value',{get:fail,set:fail,configurable:true});
 const methods=['click','focus','dispatchEvent','setAttribute','removeAttribute','appendChild','remove','replaceWith','insertBefore','replaceChild'] as const;
 const native=new Map(methods.map(method=>[method,(win.HTMLElement.prototype as any)[method]]));for(const method of methods)(win.HTMLElement.prototype as any)[method]=fail;
 Object.defineProperty(win.document,'cookie',{get:fail,configurable:true});win.document.write=fail;win.document.execCommand=fail;
 const textGetter=Object.getOwnPropertyDescriptor(win.CharacterData.prototype,'data')!.get!;
 Object.defineProperty(win.CharacterData.prototype,'data',{get:function(){if(this.parentElement!==field||state==='A')return fail();return textGetter.call(this);},set:fail,configurable:true});
 let clock=10000;let output='';const before=win.document.documentElement.outerHTML;
 const configured=source.replace("{ state: 'A', conversationRoot: $0, contactPanel: null, phoneField: null }",state==='A'?"{ state: 'A', conversationRoot: $0, contactPanel: null, phoneField: null }":"{ state: 'B', conversationRoot: $2, contactPanel: $1, phoneField: $0 }");
 try{await runInNewContext(configured,{document:win.document,$0:state==='A'?root:field,$1:panel,$2:root,console:{log:(value:string)=>{output=value;}},Date:{now:()=>clock},setTimeout:(fn:()=>void)=>{for(const method of methods)(win.HTMLElement.prototype as any)[method]=native.get(method);try{options.change?.(win.document as unknown as Document);}finally{for(const method of methods)(win.HTMLElement.prototype as any)[method]=fail;}clock+=options.delayMs??200;fn();},fetch:fail,chrome:new Proxy({},{get:fail}),localStorage:new Proxy({},{get:fail}),sessionStorage:new Proxy({},{get:fail})},{timeout:1000});if(!options.change)assert.equal(win.document.documentElement.outerHTML,before);return {output,report:JSON.parse(output)};}finally{win.close();}
}
test('STATE_A is read-only, bounded structural metadata without messages, names or composer values',async()=>{const {output,report}=await run('A');assert.equal(report.probe,'ATLAS_WHATSAPP_STRUCTURE_A');assert.equal(report.counts.composers,1);assert.equal(report.sampledNodeStability.composers,true);assert.equal(report.phoneEvidence,'NOT_VERIFIED');for(const marker of ['PRIVATE_NAME','PRIVATE_MESSAGE','PRIVATE_DRAFT','PRIVATE_URL','123456789'])assert.ok(!output.includes(marker));});
test('STATE_B reads only explicitly selected contact phone leaf and emits presence, never number',async()=>{const {output,report}=await run('B');assert.equal(report.probe,'ATLAS_WHATSAPP_STRUCTURE_B');assert.equal(report.phoneEvidence,'PRESENT');assert.equal(report.contactPanel.association,'NOT_VERIFIED');assert.equal(report.identityVerified,false);assert.equal(report.documentEpoch,'NOT_VERIFIED');assert.ok(!output.includes('123456789'));assert.ok(!output.includes('PRIVATE_CONTACT'));});
test('phone evidence cannot read conversation/history or a broad panel',async()=>{for(const options of [{phone:'conversation'},{phone:'contact'},{panel:'conversation'}]){const {report}=await run('B',options);assert.equal(report.phoneEvidence,'NOT_VERIFIED');}});
test('node replacement invalidates sampled stability even with identical metadata',async()=>{const {report}=await run('A',{change:doc=>{const old=doc.querySelector('[contenteditable]')!;old.parentNode!.replaceChild(old.cloneNode(true),old);}});assert.equal(report.sampledNodeStability.composers,false);assert.equal(report.identityVerified,false);});
test('excessive structural candidates are truncated and cannot prove stability',async()=>{const {report}=await run('A',{large:true});assert.equal(report.truncated,true);assert.equal(report.counts.buttons,40);assert.equal(report.sampledNodeStability.buttons,false);assert.ok(JSON.stringify(report).length<6000);});
test('moving same composer to another container is a structural change',async()=>{const {report}=await run('A',{change:doc=>{const composer=doc.querySelector('[contenteditable]')!,root=doc.getElementById('conversation')!;const parent=doc.createElement('section');root.insertBefore(parent,root.firstChild);parent.insertBefore(composer,null);}});assert.equal(report.sampledNodeStability.composers,false);});

test('late scheduling makes stability unverified and cannot authorize a design or identity',async()=>{const {report}=await run('B',{delayMs:1501});assert.equal(report.sampledNodeStability.durationMs,1501);assert.equal(report.sampledNodeStability.withinSamplingWindow,false);assert.equal(report.sampledNodeStability.composers,false);assert.equal(report.phoneEvidence,'NOT_VERIFIED');assert.equal(report.adapterDesignEvidence,'NOT_VERIFIED');assert.equal(report.sufficientForAdapterImplementation,false);});
