import { AttachedChromeProvider } from '../browser/attached/provider.js';
import type { BrowserTransport } from '../browser/attached/transport.js';
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { JSDOM } from 'jsdom';
import { WhatsAppSemanticAdapter } from '../../extension/src/semantic-adapters/whatsapp.js';
import { SemanticAdapterRegistry } from '../../extension/src/semantic-adapters/registry.js';
import { ContentEngine } from '../../extension/src/content-engine.js';
import { conversationEvidenceSchema, assessConversationEvidence } from '../browser/consequential/conversation-evidence.js';
import { observeTracer } from '../diagnostics/browser-observe.js';
const html='<main id="main" data-testid="conversation-panel-wrapper"><header data-testid="conversation-header" aria-label="PRIVATE_NAME">PRIVATE_NAME</header><div role="log">PRIVATE_MESSAGE</div><footer><div data-testid="conversation-compose-box-input" role="textbox" contenteditable="true">PRIVATE_DRAFT</div><button>Send</button></footer></main>';
function fixture(source=html){const dom=new JSDOM(source,{url:'https://web.whatsapp.com/',pretendToBeVisual:true}),win=dom.window;const adapter=new WhatsAppSemanticAdapter(randomUUID);const binding={tabId:randomUUID(),scopeId:randomUUID(),documentId:randomUUID(),epoch:randomUUID()};
 win.HTMLElement.prototype.checkVisibility=function(){return !this.closest('[hidden],[aria-hidden="true"]');};
 win.HTMLElement.prototype.getBoundingClientRect=function(){const x=[...win.document.querySelectorAll('*')].indexOf(this)*8;return {left:x,right:x+6,top:0,bottom:6,width:6,height:6,x,y:0,toJSON(){}};};
 win.document.elementFromPoint=x=>[...win.document.querySelectorAll('*')].find(n=>{const r=n.getBoundingClientRect();return x>=r.left&&x<=r.right;})??null;
 const read=()=>adapter.read(win.document,n=>n.checkVisibility(),binding);return {dom,win,adapter,binding,read,close:()=>win.close()};}
test('real conversation hints yield structural evidence, never individual identity proof',()=>{const f=fixture();try{const result=f.read();assert.equal(result.activePanelCandidate,true);assert.equal(result.header,true);assert.equal(result.composer,true);assert.equal(result.composerEnabled,true);assert.equal(result.conversationKind,'NOT_VERIFIED');assert.equal(result.identity,'NOT_VERIFIED');assert.equal(assessConversationEvidence(result).status,'INSUFFICIENT_EVIDENCE');}finally{f.close();}});
for(const [name,source,expected] of [
 ['absent active conversation','<div role="textbox" contenteditable="true"></div>','UNAVAILABLE'],
 ['two headers',html.replace('</header>','</header><header data-testid="conversation-header"></header>'),'INSUFFICIENT_EVIDENCE'],
 ['two composers',html.replace('</footer>','<div data-testid="conversation-compose-box-input" role="textbox" contenteditable="true"></div></footer>'),'INSUFFICIENT_EVIDENCE'],
 ['outside composer',html.replace('data-testid="conversation-compose-box-input"','')+'<div data-testid="conversation-compose-box-input" role="textbox" contenteditable="true"></div>','INSUFFICIENT_EVIDENCE'],
 ['name without phone',html,'INSUFFICIENT_EVIDENCE'],
 ['unassociated panel with visible phone',html+'<aside data-testid="contact-info"><span>+12345678901</span></aside>','INSUFFICIENT_EVIDENCE'],
 ['group indication',html.replace('PRIVATE_NAME"','Group info"'),'INSUFFICIENT_EVIDENCE']
] as const)test(name,()=>{const f=fixture(source);try{const result=f.read();assert.equal(result.state,expected);assert.equal(result.phoneEvidence,'NOT_VERIFIED');assert.equal(result.contactAssociation,'NOT_VERIFIED');assert.equal(result.identity,'NOT_VERIFIED');if(name==='group indication')assert.equal(result.conversationKind,'GROUP_INDICATED');if(name==='outside composer')assert.equal(result.composer,false);if(name==='two composers')assert.equal(result.composer,false);if(name==='two headers')assert.equal(result.header,false);}finally{f.close();}});
test('candidate panel counts never scan telephone text or infer association',()=>{const f=fixture(html+'<aside data-testid="contact-info"><span itemprop="telephone">+12345678901</span></aside>');try{Object.defineProperty(f.win.HTMLElement.prototype,'textContent',{get(){throw new Error('Private text read');},configurable:true});const result=f.read();assert.equal(result.contactCandidates,1);assert.equal(result.contactPanel,'CANDIDATE');assert.equal(result.phoneEvidence,'NOT_VERIFIED');assert.ok(!JSON.stringify(result).includes('123456789'));}finally{f.close();}});
test('backend refuses both matching-looking and different requested phones without a binding proof',async()=>{const f=fixture(html+'<aside data-testid="contact-info"><span>+12345678901</span></aside>'),session=randomUUID(),connection=randomUUID();const tab={id:f.binding.tabId,scopeId:f.binding.scopeId,url:'https://web.whatsapp.com/',title:'Test',active:true,expiresAt:Date.now()+60000,state:'ACTIVE' as const};const operations:string[]=[];
 const transport:BrowserTransport={epoch:f.binding.epoch,connections:()=>[connection],subscribe:()=>()=>{},close:()=>{},request:async(_connection,req)=>{operations.push(req.operation);if(req.operation==='listAuthorizedTabs')return {outcome:'OK',data:[tab]};if(req.operation==='observe')return {outcome:'OK',data:{tabId:tab.id,scopeId:tab.scopeId,documentId:f.binding.documentId,snapshotId:randomUUID(),expiresAt:Date.now()+15000,url:tab.url,title:'Test',elements:[],truncated:false,conversationEvidence:f.read()}};return {outcome:'ERROR',code:'REJECTED'};}};
 const provider=new AttachedChromeProvider(transport);try{await provider.inSession(session,async()=>{await provider.listTabs(new AbortController().signal);for(const phone of ['+12345678901','+98765432109']){await provider.admitGoal(randomUUID(),`Prepare a private draft for ${phone}`);const result=await provider.prepareDraft({recipientHint:'Test',recipientIdentity:phone,text:'Private text'},new AbortController().signal);assert.equal((result as {status:string}).status,'INSUFFICIENT_EVIDENCE');}assert.deepEqual(operations,['listAuthorizedTabs','observe','observe']);assert.throws(()=>conversationEvidenceSchema.parse({...f.read(),identity:'VERIFIED'}));});}finally{await provider.close();f.close();}});

for(const selector of ['[data-testid="conversation-header"]','[data-testid="conversation-compose-box-input"]','[data-testid="conversation-panel-wrapper"]'])test(`node replacement changes handle: ${selector}`,()=>{const f=fixture();try{const before=f.read();const node=f.win.document.querySelector(selector)!;node.replaceWith(node.cloneNode(true));const after=f.read();assert.notDeepEqual(before.handles,after.handles);assert.equal(after.identity,'NOT_VERIFIED');}finally{f.close();}});
test('document/epoch binding changes without restoring identity',()=>{const f=fixture();try{const before=f.read();f.binding.documentId=randomUUID();f.binding.epoch=randomUUID();const after=f.read();assert.notDeepEqual(after.binding,before.binding);assert.equal(after.identity,'NOT_VERIFIED');}finally{f.close();}});
test('adapter has no writes/field reads/network and emits no private log payload',()=>{const f=fixture();try{const fail=()=>{throw new Error('Forbidden effect');};for(const method of ['click','focus','dispatchEvent','setAttribute','removeAttribute'] as const)(f.win.HTMLElement.prototype as any)[method]=fail;Object.defineProperty(f.win.HTMLElement.prototype,'textContent',{get:fail,set:fail,configurable:true});Object.defineProperty(f.win.HTMLTextAreaElement.prototype,'value',{get:fail,set:fail,configurable:true});Object.defineProperty(f.win.document,'cookie',{get:fail,configurable:true});const result=f.read();for(const sentinel of ['PRIVATE_NAME','PRIVATE_MESSAGE','PRIVATE_DRAFT'])assert.ok(!JSON.stringify(result).includes(sentinel));const logs:unknown[]=[];observeTracer(true,row=>logs.push(row))({...result,stage:'OBSERVE_RESULT'});assert.equal(logs.length,0);}finally{f.close();}});
test('registry selects exact approved product origin only, no host logic in provider',()=>{const registry=new SemanticAdapterRegistry(randomUUID);assert.ok(registry.select('https://web.whatsapp.com'));for(const origin of ['https://whatsapp.com','https://web.whatsapp.com.evil.example','http://web.whatsapp.com','https://fixture.example'])assert.equal(registry.select(origin),undefined);});
test('content observation marks changed evidence invalidated and still blocks composer/Send',async()=>{const f=fixture();let changed=false;const engine=new ContentEngine(f.win as unknown as Window & typeof globalThis,Date.now,randomUUID,async()=>{if(!changed){changed=true;f.win.document.querySelector('header')!.setAttribute('aria-label','Group info');}});const access={scopeId:f.binding.scopeId,tabId:f.binding.tabId,session:randomUUID(),epoch:f.binding.epoch,origin:'https://web.whatsapp.com',expiresAt:Date.now()+60000};engine.initialize(access);try{const observed=await engine.run('observe',{scopeId:access.scopeId,tabId:access.tabId},Date.now()+10000,{session:access.session,epoch:access.epoch});assert.equal(observed.outcome,'OK');if(observed.outcome!=='OK'||!('elements'in observed.data))throw new Error();assert.equal(observed.data.conversationEvidence?.state,'INVALIDATED');assert.equal(observed.data.conversationEvidence?.identity,'NOT_VERIFIED');const composer=observed.data.elements.find(e=>e.role==='textbox')!;const action=await engine.run('type',{scopeId:access.scopeId,tabId:access.tabId,documentId:observed.data.documentId,snapshotId:observed.data.snapshotId,ref:composer.ref,text:'Forbidden',mode:'replace'},Date.now()+10000,{session:access.session,epoch:access.epoch});assert.equal(action.outcome,'ERROR');}finally{engine.destroy();f.close();}});

test('header text changing during READ invalidates evidence without reading name/message values',()=>{const f=fixture();try{const watch=f.adapter.watch(f.win.document);f.win.document.querySelector('header')!.firstChild!.nodeValue='CHANGED_PRIVATE_NAME';assert.equal(watch.changed(),true);watch.stop();assert.equal(f.read().identity,'NOT_VERIFIED');}finally{f.close();}});
test('observation limits do not assert uniqueness beyond the bounded scan',()=>{const f=fixture(html+'<aside>'+Array.from({length:70},()=>'<div role="dialog"></div>').join('')+'</aside>');try{const evidence=f.read();assert.equal(evidence.truncated,true);assert.equal(evidence.activePanelCandidate,false);assert.deepEqual(evidence.handles,{});assert.equal(evidence.identity,'NOT_VERIFIED');}finally{f.close();}});
