import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID as id } from 'node:crypto';
import { JSDOM } from 'jsdom';
import { ConversationObserver } from '../../extension/src/conversation-context.js';
import { ContentEngine } from '../../extension/src/content-engine.js';
import { semanticContextSchema, draftContextSchema, resolveRecipient, draftRequestSchema } from '../browser/consequential/semantic.js';
import type { DraftContext, SemanticContext } from '../browser/consequential/semantic.js';
import { ConsequentialFoundation } from '../browser/consequential/foundation.js';
import { conversationFixture } from './fixtures/semantic-conversation.js';
import { AttachedChromeProvider } from '../browser/attached/provider.js';
import type { BrowserTransport } from '../browser/attached/transport.js';
import { BrowserAdapter } from './adapters/browser.js';
import { ToolRegistry } from './registry.js';
import { ToolExecutor } from './execution.js';
import { ToolError } from './types.js';
const origin='https://messaging.example';
const request={recipientHint:'Ana',recipientIdentity:'ana@example.test',text:'Private draft exact text'};
function fixture(html=conversationFixture()) {
 const dom=new JSDOM(html,{url:origin,pretendToBeVisual:true}),win=dom.window;
 win.HTMLElement.prototype.checkVisibility=function(){return !this.closest('[hidden],[aria-hidden="true"],[inert]');};
 win.HTMLElement.prototype.getBoundingClientRect=function(){const x=[...win.document.querySelectorAll('*')].indexOf(this)*8;return {left:x,right:x+6,top:0,bottom:6,width:6,height:6,x,y:0,toJSON(){}};};
 win.document.elementFromPoint=x=>[...win.document.querySelectorAll('*')].find(n=>{const r=n.getBoundingClientRect();return x>=r.left&&x<=r.right;})??null;
 const observer=new ConversationObserver(id);
 const read=()=>observer.read(win.document,origin,n=>n.checkVisibility());
 return {dom,win,read,close:()=>win.close()};
}
function context(semantic:SemanticContext):DraftContext {const now=Date.now();return draftContextSchema.parse({backendSessionId:id(),taskId:id(),admissionId:id(),connectionEpoch:id(),origin,scopeId:id(),tabId:id(),documentId:id(),snapshotId:id(),snapshotExpiresAt:now+15_000,grantExpiresAt:now+60_000,chromePermission:true,siteAuthorized:true,grantValid:true,requestedIdentifiers:[request.recipientIdentity],semantic});}
const signal=()=>new AbortController().signal;
function frozen(result:ReturnType<ConsequentialFoundation['prepareDraft']>) {if(!('intent' in result))throw new Error('Expected frozen draft');return result;}

test('explicit visible recipient + identifier + composer relationship yields verified candidate',()=>{const f=fixture();try{const semantic=f.read();assert.equal(semantic.application,'Messaging workspace');assert.equal(semantic.trust,'UNTRUSTED_PAGE_EVIDENCE');const result=resolveRecipient(semantic,request);assert.equal(result.status,'VERIFIED');if(result.status==='VERIFIED'){assert.ok(result.conversation.composerId);assert.equal(result.conversation.sendControlIds.length,1);}}finally{f.close();}});
for(const [name,html,expected] of [
 ['homonyms need clarification',conversationFixture()+conversationFixture({id:'other',identity:'other@example.test'}),'AMBIGUOUS'],
 ['name alone is not identity',conversationFixture(),'IDENTITY_REQUIRED'],
 ['identity missing',conversationFixture({identity:''}),'INSUFFICIENT_EVIDENCE'],
 ['composer unassociated',conversationFixture({associated:false}),'INSUFFICIENT_EVIDENCE'],
 ['duplicate identity',conversationFixture()+conversationFixture({id:'other'}),'AMBIGUOUS'],
 ['title never identifies recipient','<title>Ana ana@example.test</title><textarea></textarea>','INSUFFICIENT_EVIDENCE'],
 ['hidden identity',conversationFixture().replace('itemprop="email"','hidden itemprop="email"'),'INSUFFICIENT_EVIDENCE'],
 ['duplicate DOM IDs',conversationFixture()+conversationFixture(),'INSUFFICIENT_EVIDENCE'],
 ['label containing message history is not recipient evidence','<header id="recipient"><span itemprop="name">Ana</span><span itemprop="email">ana@example.test</span><div id="chat" role="log" aria-labelledby="recipient"></div></header><textarea aria-controls="chat"></textarea>','INSUFFICIENT_EVIDENCE']
] as const)test(name,()=>{const f=fixture(html);try{const req=name==='homonyms need clarification'||name==='name alone is not identity'?{...request,recipientIdentity:undefined}:request;assert.equal(resolveRecipient(f.read(),req).status,expected);}finally{f.close();}});
test('homonym may resolve only by exact additional identity, not name uniqueness',()=>{const f=fixture(conversationFixture()+conversationFixture({id:'other',identity:'other@example.test'}));try{assert.equal(resolveRecipient(f.read(),request).status,'VERIFIED');assert.equal(resolveRecipient(f.read(),{...request,recipientIdentity:'invented@example.test'}).status,'INSUFFICIENT_EVIDENCE');}finally{f.close();}});
test('untrusted prompt injection/messages never become semantic instructions or draft content',()=>{const f=fixture(conversationFixture({injection:true}));try{const semantic=f.read();assert.ok(!JSON.stringify(semantic).includes('SECRET_MESSAGE_SENTINEL'));const c=context(semantic),foundation=ConsequentialFoundation.drafts(c.backendSessionId);const draft=frozen(foundation.prepareDraft(request,c,signal()));assert.equal(draft.intent.content.text,request.text);assert.equal(draft.executionEnabled,false);assert.equal(draft.confirmationEnabled,false);}finally{f.close();}});
test('safe draft deeply frozen; no approval hook or dispatch, even with fabricated IDs',()=>{const f=fixture();try{const c=context(f.read()),foundation=ConsequentialFoundation.drafts(c.backendSessionId),draft=frozen(foundation.prepareDraft(request,c,signal()));assert.equal(draft.status,'FROZEN');assert.equal(draft.intent.origin,origin);assert.equal(draft.intent.expiresAt,c.snapshotExpiresAt);assert.ok(Object.isFrozen(draft.intent.content));assert.ok(Object.isFrozen(draft.conversation.recipient.identifiers));assert.throws(()=>foundation.execute(draft.intent.intentId,signal()),ToolError);assert.throws(()=>foundation.simulationTool(),ToolError);assert.throws(()=>draftRequestSchema.parse({...request,executionId:id(),approved:true}));assert.equal(f.win.document.querySelector('[contenteditable]')!.textContent,'');}finally{f.close();}});
test('model cannot manufacture a user-requested identity from observed page',()=>{const f=fixture();try{const c=context(f.read());c.requestedIdentifiers=[];const foundation=ConsequentialFoundation.drafts(c.backendSessionId);assert.equal(foundation.prepareDraft(request,c,signal()).status,'IDENTITY_REQUIRED');}finally{f.close();}});
test('fresh snapshot alone preserves draft binding without extending frozen expiry',()=>{const f=fixture();try{const c=context(f.read()),foundation=ConsequentialFoundation.drafts(c.backendSessionId),draft=frozen(foundation.prepareDraft(request,c,signal()));const reviewed=foundation.reviewDraft(draft.intent.intentId,{...c,snapshotId:id(),snapshotExpiresAt:c.snapshotExpiresAt+1000});assert.equal(reviewed.status,'FROZEN');assert.equal(reviewed.intent.expiresAt,draft.intent.expiresAt);}finally{f.close();}});
for(const field of ['taskId','admissionId','connectionEpoch','scopeId','tabId','documentId','origin','recipient','composer','sendControl','conversation','revocation'] as const)test(`draft invalidated by material change: ${field}`,()=>{const f=fixture();try{const c=context(f.read()),foundation=ConsequentialFoundation.drafts(c.backendSessionId),draft=frozen(foundation.prepareDraft(request,c,signal())),changed=structuredClone(c);
 if(['taskId','admissionId','connectionEpoch','scopeId','tabId','documentId'].includes(field))(changed as any)[field]=id();else if(field==='origin'){changed.origin='https://other.example';changed.semantic.origin=changed.origin;}else if(field==='recipient')changed.semantic.conversations[0]!.recipient.identifiers[0]!.value='other@example.test';else if(field==='composer')changed.semantic.conversations[0]!.composerId=id();else if(field==='sendControl')changed.semantic.conversations[0]!.sendControlIds=[id()];else if(field==='conversation')changed.semantic.conversations=[];else if(field==='revocation')(changed as any).grantValid=false;
 assert.notEqual(foundation.reviewDraft(draft.intent.intentId,changed).status,'FROZEN');assert.throws(()=>foundation.execute(draft.intent.intentId,signal()),ToolError);
 }finally{f.close();}});
test('draft edit supersedes old preparation, does not mutate frozen message',()=>{const f=fixture();try{const c=context(f.read()),foundation=ConsequentialFoundation.drafts(c.backendSessionId),first=frozen(foundation.prepareDraft(request,c,signal())),second=frozen(foundation.prepareDraft({...request,text:'Changed exact text'},c,signal()));assert.notEqual(first.intent.intentId,second.intent.intentId);assert.equal(foundation.state(first.intent.intentId).state,'INVALIDATED');assert.equal(first.intent.content.text,request.text);assert.equal(second.intent.content.text,'Changed exact text');}finally{f.close();}});
test('expired draft and cross-session review fail safely',()=>{const f=fixture();try{const c=context(f.read());let now=Date.now();const foundation=ConsequentialFoundation.drafts(c.backendSessionId,()=>now),draft=frozen(foundation.prepareDraft(request,c,signal()));now=c.snapshotExpiresAt+1;assert.equal(foundation.reviewDraft(draft.intent.intentId,c).status,'EXPIRED');assert.throws(()=>ConsequentialFoundation.drafts(id()).reviewDraft(draft.intent.intentId,c),ToolError);}finally{f.close();}});
test('composer replacement during hydration changes opaque identity, not remapping to replacement',()=>{const f=fixture();try{const before=f.read();const composer=f.win.document.querySelector('[contenteditable]')!;composer.replaceWith(composer.cloneNode(true));const after=f.read();assert.equal(before.conversations[0]!.conversationId,after.conversations[0]!.conversationId);assert.notEqual(before.conversations[0]!.composerId,after.conversations[0]!.composerId);}finally{f.close();}});
test('truncated candidates refuse uniqueness; strict schema rejects executable capabilities',()=>{const f=fixture();try{const c=f.read();assert.equal(resolveRecipient({...c,truncated:true},request).status,'INSUFFICIENT_EVIDENCE');assert.throws(()=>semanticContextSchema.parse({...c,execute:'SEND'}));assert.throws(()=>semanticContextSchema.parse({...c,conversations:[{...c.conversations[0],selector:'#send'}]}));}finally{f.close();}});

test('actual content observe exposes semantics but Send/Enter/type remain blocked',async()=>{const f=fixture();const engine=new ContentEngine(f.win as unknown as Window & typeof globalThis,Date.now,id);const access={scopeId:id(),tabId:id(),session:id(),epoch:id(),origin,expiresAt:Date.now()+60000};engine.initialize(access);const run=(operation:Parameters<ContentEngine['run']>[0],args:Record<string,unknown>={})=>engine.run(operation,{scopeId:access.scopeId,tabId:access.tabId,...args},Date.now()+10000,{session:access.session,epoch:access.epoch});try{const observed=await run('observe');assert.equal(observed.outcome,'OK');if(observed.outcome!=='OK'||!('elements' in observed.data))throw new Error();assert.ok(observed.data.conversationContext?.conversations[0]?.composerId);const send=observed.data.elements.find(e=>e.name==='Send')!,composer=observed.data.elements.find(e=>e.role==='textbox')!;
 let count=0;f.win.document.querySelector('button')!.addEventListener('click',()=>count++);
 for(const [operation,element,extra] of [['click',send,{}],['type',composer,{text:'Do not write',mode:'replace'}],['press',composer,{key:'Enter'}]] as const){const fresh=await run('observe');if(fresh.outcome!=='OK'||!('elements'in fresh.data))throw new Error();const ref=fresh.data.elements.find(e=>e.name===element.name)!;const result=await run(operation,{documentId:fresh.data.documentId,snapshotId:fresh.data.snapshotId,ref:ref.ref,...extra});assert.equal(result.outcome,'ERROR');}
 assert.equal(count,0);assert.equal(f.win.document.querySelector('[contenteditable]')!.textContent,'');
 }finally{engine.destroy();f.close();}});

test('runtime tools freeze private draft using READ only and invalidate on real conversation change',async()=>{const f=fixture(),engine=new ContentEngine(f.win as unknown as Window & typeof globalThis,Date.now,id),session=id(),epoch=id(),scopeId=id(),tabId=id(),connection=id();const tab={id:tabId,scopeId,url:origin+'/',title:'Untrusted tab title',active:true,expiresAt:Date.now()+60000,state:'ACTIVE' as const};const operations:string[]=[];
 const transport:BrowserTransport={epoch,connections:()=>[connection],subscribe:()=>()=>{},close:()=>{},request:async(_connection,req)=>{operations.push(req.operation);if(req.operation==='listAuthorizedTabs')return {outcome:'OK',data:[tab]};if(req.operation==='observe'){engine.initialize({scopeId,tabId,session,epoch,origin,expiresAt:tab.expiresAt});return engine.run('observe',req.args,req.deadlineAt,{session,epoch});}return {outcome:'ERROR',code:'REJECTED'};}};
 const provider=new AttachedChromeProvider(transport),adapter=new BrowserAdapter(provider),registry=new ToolRegistry();registry.add(adapter);const executor=new ToolExecutor(registry);
 try{await adapter.inSession(session,async()=>{await adapter.admitGoal(id(),'Prepará un borrador para Ana ana@example.test');await provider.listTabs(signal());const prepared=await executor.invoke(id(),'browser.prepareDraft',request);assert.equal(prepared.status,'success');if(prepared.status!=='success')throw new Error();const draft=prepared.data as {intent:{intentId:string};status:string};assert.equal(draft.status,'FROZEN');assert.equal(executor.pendingState(),null);
 f.win.document.querySelector('[itemprop="email"]')!.textContent='other@example.test';const reviewed=await executor.invoke(id(),'browser.reviewDraft',{intentId:draft.intent.intentId});assert.equal(reviewed.status,'success');if(reviewed.status==='success')assert.equal((reviewed.data as {status:string}).status,'INVALIDATED');
 assert.deepEqual(operations,['listAuthorizedTabs','observe','observe']);assert.ok(!registry.resolve('browser.send'));assert.ok(!registry.resolve('browser.simulateSendMessage'));
 });}finally{await provider.close();engine.destroy();f.close();}});

test('connection epoch changing during draft READ cannot freeze old document evidence',async()=>{const f=fixture(),session=id(),connection=id(),tabId=id(),scopeId=id();let epoch=id();const operations:string[]=[];const tab={id:tabId,scopeId,url:origin+'/',title:'Tab',active:true,expiresAt:Date.now()+60000,state:'ACTIVE' as const};
 const transport:BrowserTransport={get epoch(){return epoch;},connections:()=>[connection],subscribe:()=>()=>{},close:()=>{},request:async(_connection,req)=>{operations.push(req.operation);if(req.operation==='listAuthorizedTabs')return {outcome:'OK',data:[tab]};if(req.operation==='observe'){epoch=id();return {outcome:'OK',data:{tabId,scopeId,documentId:id(),snapshotId:id(),expiresAt:Date.now()+15000,url:origin+'/',title:'Tab',elements:[],truncated:false,conversationContext:f.read()}};}return {outcome:'ERROR',code:'REJECTED'};}};
 const provider=new AttachedChromeProvider(transport);try{await provider.inSession(session,async()=>{await provider.admitGoal(id(),'Borrador para Ana ana@example.test');await provider.listTabs(signal());await assert.rejects(provider.prepareDraft(request,signal()),(error:unknown)=>error instanceof ToolError&&error.category==='REJECTED');assert.deepEqual(operations,['listAuthorizedTabs','observe']);});}finally{await provider.close();f.close();}});
