import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdtemp,readFile,rm,chmod,lstat,symlink,link,writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { RunContext } from '@openai/agents-core';
import { candidateSchema,resultSchema } from '../browser/consequential/contracts.js';
import type { TrustedContext } from '../browser/consequential/contracts.js';
import { ConsequentialFoundation } from '../browser/consequential/foundation.js';
import { PrivateExecutionJournal } from '../browser/consequential/journal.js';
import { ToolRegistry } from './registry.js';
import { ToolExecutor } from './execution.js';
import { VoiceToolBridge } from '../provider/tools.js';
import { ToolError } from './types.js';
const uuid=randomUUID;
async function fixture(){const root=await mkdtemp(join(tmpdir(),'atlas-consequential-'));const path=join(root,'private','journal.json');let now=Date.now();let calls=0;let effect:()=>Promise<{simulationOnly:true;evidence:'SIMULATED_MESSAGE_ACCEPTED'}>=async()=>({simulationOnly:true,evidence:'SIMULATED_MESSAGE_ACCEPTED'});
 const context:TrustedContext={chromePermission:true,siteAuthorized:true,grantValid:true,grantExpiresAt:now+900_000,candidate:candidateSchema.parse({backendSessionId:uuid(),taskId:uuid(),admissionId:uuid(),connectionEpoch:uuid(),origin:'https://fixture.example',scopeId:uuid(),tabId:uuid(),documentId:uuid(),preparationId:uuid(),recipient:{identity:'fixture-recipient',displayName:'Fixture',evidenceId:uuid(),uniqueness:'PROVEN'},content:{text:'private-test-message'}})};
 let executor:ToolExecutor;let observe=async()=>structuredClone(context);const journal=new PrivateExecutionJournal(path);const make=()=>new ConsequentialFoundation(journal,()=>observe(),context.candidate.backendSessionId,{simulationOnly:true,execute:async()=>{calls++;return effect();}},()=>now,confirmationId=>{if(executor?.pendingState()?.confirmationId===confirmationId)executor.invalidate();});
 const foundation=make();await foundation.initialize();const registry=new ToolRegistry();registry.register(foundation.simulationTool());executor=new ToolExecutor(registry,()=>now);const request={recipientHint:'Fixture',text:'private-test-message'};
 const prepare=async()=>{const result=await executor.invoke(uuid(),'browser.simulateSendMessage',request);assert.equal(result.status,'pending');if(result.status!=='pending')throw new Error();return result;};
 return {root,path,context,journal,foundation,registry,executor,request,prepare,calls:()=>calls,setEffect:(fn:typeof effect)=>{effect=fn;},setObserve:(fn:typeof observe)=>{observe=fn;},advance:()=>{now+=60_001;},now:()=>now,restart:async()=>{const next=make();await next.initialize();return next;},close:async()=>{executor.close();await rm(root,{recursive:true,force:true});}};
}
test('consequential simulation reuses SENSITIVE confirmation; approval binds exact frozen action and executes once',async()=>{const f=await fixture();try{const p=await f.prepare();assert.equal(f.calls(),0);assert.ok(p.summary.includes('private-test-message'));assert.ok(p.summary.includes('SIMULACIÓN'));const r=await f.executor.decide(p.confirmationId,true);assert.equal(r.status,'success');if(r.status!=='success')throw new Error();const result=resultSchema.parse(r.data);assert.equal(result.outcome,'CONFIRMED_SUCCESS');assert.equal(result.simulationOnly,true);assert.equal(f.calls(),1);assert.equal((await f.executor.decide(p.confirmationId,true)).status,'error');assert.equal(f.calls(),1);const journal=await readFile(f.path,'utf8');for(const secret of ['private-test-message','fixture-recipient','Fixture','confirmationId','chrome','content','recipient'])assert.ok(!journal.includes(secret));}finally{await f.close();}});
for(const mode of ['reject','expire','cancel'] as const)test(`consequential ${mode} never reaches simulated dispatch`,async()=>{const f=await fixture();try{const p=await f.prepare();if(mode==='expire')f.advance();if(mode==='cancel')f.executor.invalidate();const r=await f.executor.decide(p.confirmationId,mode!=='reject');assert.equal(r.status,'error');assert.equal(f.calls(),0);}finally{await f.close();}});
test('concurrent decisions consume one confirmation before any await',async()=>{const f=await fixture();try{const p=await f.prepare();const results=await Promise.all([f.executor.decide(p.confirmationId,true),f.executor.decide(p.confirmationId,true)]);assert.equal(results.filter(r=>r.status==='success').length,1);assert.equal(f.calls(),1);}finally{await f.close();}});
for(const field of ['content','recipient','epoch','origin','scope','document','task','admission','preparation','session','chromePermission','siteAuthorized','grantValid'] as const)test(`revalidation refuses changed ${field} without dispatch`,async()=>{const f=await fixture();try{const p=await f.prepare();const c=f.context.candidate;if(field==='content')c.content.text='changed';else if(field==='recipient')c.recipient.identity='other';else if(field==='epoch')c.connectionEpoch=uuid();else if(field==='origin')c.origin='https://other.example';else if(field==='scope')c.scopeId=uuid();else if(field==='document')c.documentId=uuid();else if(field==='task')c.taskId=uuid();else if(field==='admission')c.admissionId=uuid();else if(field==='preparation')c.preparationId=uuid();else if(field==='session')c.backendSessionId=uuid();else f.context[field]=false;const r=await f.executor.decide(p.confirmationId,true);assert.equal(f.calls(),0);assert.equal(r.status,'success');if(r.status==='success')assert.equal(resultSchema.parse(r.data).execution,'NOT_EXECUTED');}finally{await f.close();}});
test('unapproved execute and model-supplied approval/execution IDs are rejected',async()=>{const f=await fixture();try{const p=await f.foundation.prepare(f.request,new AbortController().signal);assert.throws(()=>f.foundation.execute(p.intentId,new AbortController().signal),ToolError);const r=await f.executor.invoke(uuid(),'browser.simulateSendMessage',{...f.request,approved:true,executionId:uuid()});assert.equal(r.status,'error');assert.equal(f.calls(),0);}finally{await f.close();}});
test('replaying a completed execution returns the recorded result without another callback',async()=>{const f=await fixture();try{const p=await f.prepare();const r=await f.executor.decide(p.confirmationId,true);if(r.status!=='success')throw new Error();const result=resultSchema.parse(r.data);const again=await f.foundation.execute(result.intentId,new AbortController().signal);assert.deepEqual(again,result);assert.equal(f.calls(),1);await assert.rejects(f.journal.reserve({intentId:result.intentId,executionId:result.executionId!,state:'RESERVED',updatedAt:f.now()}),ToolError);}finally{await f.close();}});
test('lost simulated result is UNKNOWN and cannot create an automatic resend, including restart',async()=>{const f=await fixture();try{f.setEffect(async()=>{throw new Error('PRIVATE upstream');});const p=await f.prepare();const r=await f.executor.decide(p.confirmationId,true);if(r.status!=='success')throw new Error();const result=resultSchema.parse(r.data);assert.equal(result.outcome,'EXECUTION_UNKNOWN');assert.equal(f.calls(),1);assert.deepEqual(await f.foundation.execute(result.intentId,new AbortController().signal),result);assert.equal(f.calls(),1);const restart=await f.restart();assert.equal(restart.recoveredState(result.intentId),'UNKNOWN');await assert.rejects(restart.prepare(f.request,new AbortController().signal),ToolError);assert.throws(()=>restart.execute(result.intentId,new AbortController().signal),ToolError);assert.equal(f.calls(),1);}finally{await f.close();}});
test('restart of persisted RESERVED has UNKNOWN only; no approval or payload restored',async()=>{const f=await fixture();try{const intentId=uuid();await f.journal.reserve({intentId,executionId:uuid(),state:'RESERVED',updatedAt:f.now()});const restarted=await f.restart();assert.equal(restarted.recoveredState(intentId),'UNKNOWN');assert.equal(JSON.parse(await readFile(f.path,'utf8')).entries[0].state,'UNKNOWN');assert.equal(f.calls(),0);}finally{await f.close();}});
test('cancel before reservation is known not executed; cancellation after possible dispatch is UNKNOWN',async()=>{const f=await fixture();try{let id='';f.setObserve(async()=>{if(id)f.foundation.invalidate(id);return structuredClone(f.context);});const prepared=await f.foundation.prepare(f.request,new AbortController().signal);id=prepared.intentId;f.foundation.invalidate(id);assert.equal((await f.foundation.execute(id,new AbortController().signal)).execution,'NOT_EXECUTED');assert.equal(f.calls(),0);}finally{await f.close();}
 const g=await fixture();try{let release!:(x:{simulationOnly:true;evidence:'SIMULATED_MESSAGE_ACCEPTED'})=>void;g.setEffect(()=>new Promise(resolve=>{release=resolve;}));const p=await g.prepare();const work=g.executor.decide(p.confirmationId,true);while(g.calls()===0)await new Promise(resolve=>setTimeout(resolve,1));const rows=JSON.parse(await readFile(g.path,'utf8')).entries;g.foundation.invalidate(rows[0].intentId);release({simulationOnly:true,evidence:'SIMULATED_MESSAGE_ACCEPTED'});const r=await work;if(r.status!=='success')throw new Error();assert.equal(resultSchema.parse(r.data).outcome,'EXECUTION_UNKNOWN');assert.equal(g.calls(),1);}finally{await g.close();}});
test('aborted signal before dispatch is failure; after dispatch is UNKNOWN and never retries',async()=>{const f=await fixture();try{const p=await f.foundation.prepare(f.request,new AbortController().signal);const tool=f.foundation.simulationTool();const confirmation=uuid();tool.confirmationLifecycle!.pending(p,confirmation,f.now()+60000);tool.confirmationLifecycle!.decided(p,confirmation,true);const controller=new AbortController();controller.abort();assert.equal((await f.foundation.execute(p.intentId,controller.signal)).execution,'NOT_EXECUTED');assert.equal(f.calls(),0);}finally{await f.close();}
 const g=await fixture();try{g.setEffect(async()=>{throw new ToolError('TIMEOUT');});const p=await g.prepare();const r=await g.executor.decide(p.confirmationId,true);if(r.status!=='success')throw new Error();assert.equal(resultSchema.parse(r.data).outcome,'EXECUTION_UNKNOWN');assert.equal(g.calls(),1);}finally{await g.close();}});
test('journal persists before callback, with private file/directory security',async()=>{const f=await fixture();try{f.setEffect(async()=>{const saved=JSON.parse(await readFile(f.path,'utf8'));assert.equal(saved.entries[0].state,'RESERVED');if(process.platform!=='win32'){assert.equal((await lstat(f.path)).mode&0o777,0o600);assert.equal((await lstat(join(f.root,'private'))).mode&0o777,0o700);}return {simulationOnly:true,evidence:'SIMULATED_MESSAGE_ACCEPTED'};});const p=await f.prepare();await f.executor.decide(p.confirmationId,true);assert.equal(f.calls(),1);}finally{await f.close();}});
test('journal rejects corrupt data, symlinks, hard links and insecure POSIX modes',async()=>{const f=await fixture();try{await f.journal.reserve({intentId:uuid(),executionId:uuid(),state:'RESERVED',updatedAt:f.now()});const alias=join(f.root,'private','alias.json');await link(f.path,alias);await assert.rejects(new PrivateExecutionJournal(f.path).recover(),ToolError);await rm(alias);if(process.platform!=='win32'){await symlink(f.path,alias);await assert.rejects(new PrivateExecutionJournal(alias).recover(),ToolError);await rm(alias);await chmod(f.path,0o644);await assert.rejects(new PrivateExecutionJournal(f.path).recover(),ToolError);await chmod(f.path,0o600);}await writeFile(f.path,'{"version":1,"entries":[],"content":"PRIVATE"}');await assert.rejects(new PrivateExecutionJournal(f.path).recover(),ToolError);}finally{await f.close();}});
test('voice started before prompt completion cannot approve consequential simulation',async()=>{const f=await fixture();const original=globalThis.fetch;const notices:string[]=[];const bridge=new VoiceToolBridge(()=>{},message=>notices.push(message));try{globalThis.fetch=async(url,options)=>{const path=String(url).split('/').pop();const body=options?.body?JSON.parse(String(options.body)):{};if(path==='session')return Response.json({tools:f.registry.descriptors(),timezone:'Europe/Madrid',now:new Date().toISOString()});if(path==='invoke')return Response.json(await f.executor.invoke(body.invocationId,body.toolId,body.input));if(path==='activity')return Response.json({activity:f.executor.telemetry.snapshot(),pending:f.executor.pendingState()});if(path==='intent')return Response.json({confirmationId:body.confirmationId,intent:'affirmative'});if(path==='decision')return Response.json(await f.executor.decide(body.confirmationId,body.approved));throw new Error();};const config=await bridge.initialize();await config.tools[0]!.invoke(new RunContext(),JSON.stringify({inputJson:JSON.stringify(f.request)}));await bridge.transportEvent({type:'response.created',response:{id:'confirmation-response'}});await bridge.transportEvent({type:'input_audio_buffer.speech_started',item_id:'early'});await bridge.transportEvent({type:'output_audio_buffer.stopped',response_id:'confirmation-response'});await bridge.transportEvent({type:'conversation.item.input_audio_transcription.completed',item_id:'early',transcript:'sí'});assert.equal(f.calls(),0);assert.ok(bridge.pending);await bridge.transportEvent({type:'input_audio_buffer.speech_started',item_id:'eligible'});await bridge.transportEvent({type:'conversation.item.input_audio_transcription.completed',item_id:'eligible',transcript:'sí'});assert.equal(f.calls(),1);}finally{bridge.close();globalThis.fetch=original;await f.close();}});

test('real cancellation after simulated dispatch returns UNKNOWN even when executor ignores its AbortSignal',async()=>{const f=await fixture();try{f.setEffect(()=>new Promise(()=>{}));const raw=await f.foundation.prepare(f.request,new AbortController().signal);const tool=f.foundation.simulationTool();const confirmation=uuid();tool.confirmationLifecycle!.pending(raw,confirmation,f.now()+60000);tool.confirmationLifecycle!.decided(raw,confirmation,true);const controller=new AbortController();const work=f.foundation.execute(raw.intentId,controller.signal);while(f.calls()===0)await new Promise(resolve=>setTimeout(resolve,1));controller.abort();const result=await work;assert.equal(result.outcome,'EXECUTION_UNKNOWN');assert.equal(f.calls(),1);assert.deepEqual(await f.foundation.execute(raw.intentId,new AbortController().signal),result);assert.equal(f.calls(),1);}finally{await f.close();}});

test('explicit revocation invalidates the existing executor pending confirmation without replacing its authority',async()=>{const f=await fixture();try{const pending=await f.prepare();const prepareRow=f.executor.telemetry.snapshot()[0]!;assert.equal(prepareRow.confirmation,'waiting');const raw=await f.foundation.prepare(f.request,new AbortController().signal);assert.notEqual(raw.intentId,pending.confirmationId); // model input cannot select an approval ID
// Use the intent belonging to the pending action, captured by its trusted hook.
const tool=f.registry.resolve('browser.simulateSendMessage')!;const original=tool.confirmationLifecycle!.pending;let intentId='';tool.confirmationLifecycle!.pending=(input,id,expiry)=>{intentId=(input as {intentId:string}).intentId;original(input,id,expiry);};f.executor.invalidate();const next=await f.prepare();f.foundation.invalidate(intentId,'ACCESS_REVOKED');assert.equal(f.executor.pendingState(),null);assert.equal((await f.executor.decide(next.confirmationId,true)).status,'error');assert.equal(f.calls(),0);}finally{await f.close();}});

test('deadline expiring during revalidation prevents journal reservation and dispatch',async()=>{const f=await fixture();try{const p=await f.prepare();f.setObserve(async()=>{f.advance();return structuredClone(f.context);});const r=await f.executor.decide(p.confirmationId,true);if(r.status!=='success')throw new Error();assert.equal(resultSchema.parse(r.data).execution,'NOT_EXECUTED');assert.equal(f.calls(),0);await assert.rejects(readFile(f.path,'utf8'));}finally{await f.close();}});
test('untrusted candidate/result structures cannot declare false success or override bindings',()=>{const raw={intentId:uuid(),simulationOnly:true,execution:'NOT_EXECUTED',verification:'VERIFIED',outcome:'CONFIRMED_SUCCESS',reason:'SIMULATED_EFFECT'};assert.equal(resultSchema.safeParse(raw).success,false);assert.equal(candidateSchema.safeParse({approved:true}).success,false);});
test('late simulated completion cannot change a recorded UNKNOWN outcome',async()=>{const f=await fixture();try{let release!:(value:{simulationOnly:true;evidence:'SIMULATED_MESSAGE_ACCEPTED'})=>void;f.setEffect(()=>new Promise(resolve=>{release=resolve;}));const raw=await f.foundation.prepare(f.request,new AbortController().signal);const tool=f.foundation.simulationTool();const confirmation=uuid();tool.confirmationLifecycle!.pending(raw,confirmation,f.now()+60000);tool.confirmationLifecycle!.decided(raw,confirmation,true);const controller=new AbortController();const work=f.foundation.execute(raw.intentId,controller.signal);while(f.calls()===0)await new Promise(resolve=>setTimeout(resolve,1));controller.abort();const unknown=await work;release({simulationOnly:true,evidence:'SIMULATED_MESSAGE_ACCEPTED'});await new Promise(resolve=>setTimeout(resolve,0));assert.equal(f.foundation.state(raw.intentId).state,'UNKNOWN');assert.deepEqual(await f.foundation.execute(raw.intentId,new AbortController().signal),unknown);assert.equal(f.calls(),1);}finally{await f.close();}});

for(const change of ['grant','epoch','recipient','content'] as const)test(`revalidation after journal I/O catches ${change} changes before any possible dispatch`,async()=>{const f=await fixture();try{const reserve=f.journal.reserve.bind(f.journal);f.journal.reserve=async row=>{await reserve(row);if(change==='grant')f.context.grantValid=false;else if(change==='epoch')f.context.candidate.connectionEpoch=uuid();else if(change==='recipient')f.context.candidate.recipient.identity='other';else f.context.candidate.content.text='changed';};const p=await f.prepare();const r=await f.executor.decide(p.confirmationId,true);if(r.status!=='success')throw new Error();assert.equal(resultSchema.parse(r.data).execution,'NOT_EXECUTED');assert.equal(f.calls(),0);assert.equal(JSON.parse(await readFile(f.path,'utf8')).entries[0].state,'FAILURE');}finally{await f.close();}});
test('journal failure before dispatch cannot claim an uncertain external effect or invoke the simulator',async()=>{const f=await fixture();try{f.journal.reserve=async()=>{throw new Error('PRIVATE storage failure');};const p=await f.prepare();const r=await f.executor.decide(p.confirmationId,true);if(r.status!=='success')throw new Error();const result=resultSchema.parse(r.data);assert.equal(result.outcome,'CONFIRMED_FAILURE');assert.equal(result.execution,'NOT_EXECUTED');assert.ok(!JSON.stringify(result).includes('PRIVATE'));assert.equal(f.calls(),0);}finally{await f.close();}});

test('late cancellation during SUCCESS journal finalization cannot erase verified execution',async()=>{const f=await fixture();try{const controller=new AbortController();const finish=f.journal.finish.bind(f.journal);f.journal.finish=async(id,state,now)=>{await finish(id,state,now);controller.abort();};const raw=await f.foundation.prepare(f.request,controller.signal);const tool=f.foundation.simulationTool();const confirmation=uuid();tool.confirmationLifecycle!.pending(raw,confirmation,f.now()+60000);tool.confirmationLifecycle!.decided(raw,confirmation,true);const result=await f.foundation.execute(raw.intentId,controller.signal);assert.equal(result.outcome,'CONFIRMED_SUCCESS');assert.equal(f.foundation.state(raw.intentId).state,'SUCCESS');assert.equal(f.calls(),1);assert.equal(JSON.parse(await readFile(f.path,'utf8')).entries[0].state,'SUCCESS');}finally{await f.close();}});
